[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
birex_core = "37pwz8ZyR8wZ8KteXcX6cr4oEmguL9miwPMzHGZBGELp"
bt_token = "2Jts3AVjULjhJBsQBWHCQCRpZ4F9PX3odewcbN4hKrXi"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"

[hooks]
